
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author matthew
 */
public class SpeedGogglesGUI extends javax.swing.JFrame {

    String athlete = "Andrew Sell";
    String andrewText = ""; // very temporary cahnge to Runner runner data
    String ianText = ""; // very temporary cahnge to Runner runner data
    String lukeText = ""; // very temporary cahnge to Runner runner data
    String raymondText = ""; // very temporary cahnge to Runner runner data
            
    Boolean change = false;
    
    public SpeedGogglesGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        findTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameComboBox = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();
        submitTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageText = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Speed Goggles Chat");

        jLabel2.setText("Name:");

        nameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Andrew Sell", "Ian Adams", "Luke Michels", "Raymond Friend" }));
        nameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameComboBoxActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        submitTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitTextFieldActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(messageText);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(submitTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(nameComboBox, 0, 333, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitButton)
                .addContainerGap())
        );

        findTab.addTab("Matches", jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        findTab.addTab("Find friends", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(findTab)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(findTab, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitTextFieldActionPerformed
        setMessage(); 
    }//GEN-LAST:event_submitTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        setMessage();    
        /*
        switch(athlete){  //change from static string to Runner runner, with name
                case "Andrew":
                    messageText.setText(andrewText + "\n" + submitTextField.getText()); 
                    submitTextField.setText("");
                    andrewText = messageText.getText();
                    break;
                case "Ian Adams":
                    messageText.setText(ianText + "\n" + submitTextField.getText()); 
                    submitTextField.setText("");
                    ianText = messageText.getText();
                    break;
                case "Luke Michels":
                    messageText.setText(lukeText + "\n" + submitTextField.getText()); 
                    submitTextField.setText("");
                    lukeText = messageText.getText();
                    break;
                case "Raymond Friend":
                    messageText.setText(raymondText + "\n" + submitTextField.getText()); 
                    submitTextField.setText("");
                    raymondText = messageText.getText();
                    break;
            }
        */  
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void nameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameComboBoxActionPerformed
        athlete = (String)nameComboBox.getSelectedItem();
        //setMessage();
        if(athlete.equals("Andrew Sell")){
            messageText.setText(andrewText);
        } else if(athlete.equals("Ian Adams")){
            messageText.setText(ianText);
        } else if(athlete.equals("Luke Michels")){
            messageText.setText(lukeText);
        } else if(athlete.equals("Raymond Adams")){
            messageText.setText(raymondText);
        }
        //System.out.println("trace");
    }//GEN-LAST:event_nameComboBoxActionPerformed
    
    private void setMessage(){
        String timeStamp = getCurrentTimeStamp();
        if(athlete.equals("Andrew Sell")){
            messageText.setText(andrewText + "\n" + timeStamp + ": " + submitTextField.getText()); 
            submitTextField.setText("");
            andrewText = messageText.getText();
        } else if(athlete.equals("Ian Adams")){
            messageText.setText(ianText + "\n" + timeStamp + ": " + submitTextField.getText()); 
            submitTextField.setText("");
            ianText = messageText.getText();
        } else if(athlete.equals("Luke Michels")){
            messageText.setText(lukeText + "\n" + timeStamp + ": " + submitTextField.getText()); 
            submitTextField.setText("");
            lukeText = messageText.getText();
        } else if(athlete.equals("Raymond Friend")){
            messageText.setText(raymondText + "\n" + timeStamp + ": " + submitTextField.getText()); 
            submitTextField.setText("");
            raymondText = messageText.getText();
        }
        else{
            messageText.setText(messageText + "\n" + submitTextField.getText()); 
            submitTextField.setText("");
        }
    }
    
    public static String getCurrentTimeStamp() {
        SimpleDateFormat time = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");//dd/MM/yyyy
        Date now = new Date();
        String strDate = time.format(now);
        return strDate;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpeedGogglesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpeedGogglesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpeedGogglesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpeedGogglesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpeedGogglesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane findTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane messageText;
    private javax.swing.JComboBox<String> nameComboBox;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField submitTextField;
    // End of variables declaration//GEN-END:variables
}
